Fix script for filtering compilation database
on windows was err:

Traceback (most recent call last):
  File "cut_json.py", line 31, in <module>
    open("filtered_" + json_file_path, 'w') as json_file_out, \
IOError: [Errno 2] No such file or directory: 'filtered_out/Release_GN_x64/compile_commands.json'

(cherry picked from commit 01ba669a5f447814051107a34439be726da1954f)